
CREATE TABLE Adresse (
    AdresseID      BIGINT IDENTITY(1,1) NOT NULL,
    ByID			BIGINT NOT NULL,
    Vej  NVARCHAR(MAX) NOT NULL,
    Husnummer   NVARCHAR(MAX) NOT NULL,
CONSTRAINT pk_Adresse PRIMARY KEY CLUSTERED (AdresseID),
CONSTRAINT fk_Adresse FOREIGN KEY (ByID)
    REFERENCES Byy (ByID)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)