CREATE TABLE Byy (
    ByID         BIGINT IDENTITY(1,1) NOT NULL,
    Postnummer     NVARCHAR(MAX) NOT NULL,
    Land        NVARCHAR(MAX) NOT NULL,
    Bynavn       NVARCHAR(MAX) NOT NULL,
CONSTRAINT pk_By PRIMARY KEY CLUSTERED (ByID))