CREATE TABLE Emailadresse (
  EmailID       BIGINT IDENTITY(1,1) NOT NULL,
  PersonID		BIGINT NOT NULL, 
  Email			NVARCHAR(MAX) NOT NULL 
	CONSTRAINT pk_Email PRIMARY KEY CLUSTERED (EmailID),
	CONSTRAINT fk_Email FOREIGN KEY (PersonID)
    REFERENCES Person (PersonID)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)

