CREATE TABLE Noter (
  NoterID       BIGINT IDENTITY(1,1) NOT NULL,
  Note			NVARCHAR(MAX) NOT NULL,
  PersonID		BIGINT NOT NULL,

CONSTRAINT pk_Note PRIMARY KEY CLUSTERED (NoterID),
CONSTRAINT fk_Note FOREIGN KEY (PersonID)
    REFERENCES Person (PersonID)
    ON DELETE CASCADE
    ON UPDATE CASCADE)