CREATE TABLE Person (
  PersonID		BIGINT IDENTITY(1,1) NOT NULL, 
  AdresseID    BIGINT NOT NULL, 
  Fornavn		NVARCHAR(MAX) NOT NULL, 
  Mellemnavn	NVARCHAR(MAX) NOT NULL, 
  Efternavn		NVARCHAR(MAX) NOT NULL, 
  Type			NVARCHAR(MAX) NOT NULL, 

	CONSTRAINT pk_Person PRIMARY KEY CLUSTERED (PersonID),
	CONSTRAINT fk_Person FOREIGN KEY (AdresseID)
		REFERENCES Adresse (AdresseID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION)
